#!/bin/sh
#
# Utility to truncate the .shstrtab section from the end of the ELF file
# Really crude, don't use this technique on ELF binaries generated by
# a proper compiler
#
# by Saumil Shah

if [ "$1" = "" ]
then
   echo "Usage: $0 <binary>"
   exit
fi

offset=$(grep --byte-offset --only-matching --text '.shstrtab' "$1" | cut -d':' -f1)
dd bs=1 count=$offset if=$1 of=$$.tmp
mv $$.tmp $1
chmod +x $1
